//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/KeyboardInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @KeyboardInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @KeyboardInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""KeyboardInput"",
    ""maps"": [
        {
            ""name"": ""Default"",
            ""id"": ""1e5957d3-d710-465f-9966-acf14217a3aa"",
            ""actions"": [
                {
                    ""name"": ""CycleTakeUp"",
                    ""type"": ""Button"",
                    ""id"": ""693c69db-de9d-41de-b6aa-88759e3c7033"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CycleTakeDown"",
                    ""type"": ""Button"",
                    ""id"": ""9f5311fa-4699-4423-882b-59bb7d9e5fa8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CycleReceiveUp"",
                    ""type"": ""Button"",
                    ""id"": ""871a0629-4b99-48b2-b647-2213d18282f9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CycleReceiveDown"",
                    ""type"": ""Button"",
                    ""id"": ""1817a4df-2756-4f6d-aa9b-1704ab8eaad5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SendWater"",
                    ""type"": ""Button"",
                    ""id"": ""5c0a60e5-ee2f-42a4-9f1f-a35f26effccd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""829fbcf7-fa52-4b2f-b3b7-56a3857f5c41"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CycleTakeUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59a61521-3c5f-43a5-abc6-047afdf9111e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CycleTakeDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a16e2274-87db-4b70-8997-66c4917c4079"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CycleReceiveUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ceec9e95-99c1-4f19-badb-dd299660660a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CycleReceiveDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65059221-580e-4f3f-8952-eedc4c5a348a"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SendWater"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Default
        m_Default = asset.FindActionMap("Default", throwIfNotFound: true);
        m_Default_CycleTakeUp = m_Default.FindAction("CycleTakeUp", throwIfNotFound: true);
        m_Default_CycleTakeDown = m_Default.FindAction("CycleTakeDown", throwIfNotFound: true);
        m_Default_CycleReceiveUp = m_Default.FindAction("CycleReceiveUp", throwIfNotFound: true);
        m_Default_CycleReceiveDown = m_Default.FindAction("CycleReceiveDown", throwIfNotFound: true);
        m_Default_SendWater = m_Default.FindAction("SendWater", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Default
    private readonly InputActionMap m_Default;
    private List<IDefaultActions> m_DefaultActionsCallbackInterfaces = new List<IDefaultActions>();
    private readonly InputAction m_Default_CycleTakeUp;
    private readonly InputAction m_Default_CycleTakeDown;
    private readonly InputAction m_Default_CycleReceiveUp;
    private readonly InputAction m_Default_CycleReceiveDown;
    private readonly InputAction m_Default_SendWater;
    public struct DefaultActions
    {
        private @KeyboardInput m_Wrapper;
        public DefaultActions(@KeyboardInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @CycleTakeUp => m_Wrapper.m_Default_CycleTakeUp;
        public InputAction @CycleTakeDown => m_Wrapper.m_Default_CycleTakeDown;
        public InputAction @CycleReceiveUp => m_Wrapper.m_Default_CycleReceiveUp;
        public InputAction @CycleReceiveDown => m_Wrapper.m_Default_CycleReceiveDown;
        public InputAction @SendWater => m_Wrapper.m_Default_SendWater;
        public InputActionMap Get() { return m_Wrapper.m_Default; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultActions set) { return set.Get(); }
        public void AddCallbacks(IDefaultActions instance)
        {
            if (instance == null || m_Wrapper.m_DefaultActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DefaultActionsCallbackInterfaces.Add(instance);
            @CycleTakeUp.started += instance.OnCycleTakeUp;
            @CycleTakeUp.performed += instance.OnCycleTakeUp;
            @CycleTakeUp.canceled += instance.OnCycleTakeUp;
            @CycleTakeDown.started += instance.OnCycleTakeDown;
            @CycleTakeDown.performed += instance.OnCycleTakeDown;
            @CycleTakeDown.canceled += instance.OnCycleTakeDown;
            @CycleReceiveUp.started += instance.OnCycleReceiveUp;
            @CycleReceiveUp.performed += instance.OnCycleReceiveUp;
            @CycleReceiveUp.canceled += instance.OnCycleReceiveUp;
            @CycleReceiveDown.started += instance.OnCycleReceiveDown;
            @CycleReceiveDown.performed += instance.OnCycleReceiveDown;
            @CycleReceiveDown.canceled += instance.OnCycleReceiveDown;
            @SendWater.started += instance.OnSendWater;
            @SendWater.performed += instance.OnSendWater;
            @SendWater.canceled += instance.OnSendWater;
        }

        private void UnregisterCallbacks(IDefaultActions instance)
        {
            @CycleTakeUp.started -= instance.OnCycleTakeUp;
            @CycleTakeUp.performed -= instance.OnCycleTakeUp;
            @CycleTakeUp.canceled -= instance.OnCycleTakeUp;
            @CycleTakeDown.started -= instance.OnCycleTakeDown;
            @CycleTakeDown.performed -= instance.OnCycleTakeDown;
            @CycleTakeDown.canceled -= instance.OnCycleTakeDown;
            @CycleReceiveUp.started -= instance.OnCycleReceiveUp;
            @CycleReceiveUp.performed -= instance.OnCycleReceiveUp;
            @CycleReceiveUp.canceled -= instance.OnCycleReceiveUp;
            @CycleReceiveDown.started -= instance.OnCycleReceiveDown;
            @CycleReceiveDown.performed -= instance.OnCycleReceiveDown;
            @CycleReceiveDown.canceled -= instance.OnCycleReceiveDown;
            @SendWater.started -= instance.OnSendWater;
            @SendWater.performed -= instance.OnSendWater;
            @SendWater.canceled -= instance.OnSendWater;
        }

        public void RemoveCallbacks(IDefaultActions instance)
        {
            if (m_Wrapper.m_DefaultActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDefaultActions instance)
        {
            foreach (var item in m_Wrapper.m_DefaultActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DefaultActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DefaultActions @Default => new DefaultActions(this);
    public interface IDefaultActions
    {
        void OnCycleTakeUp(InputAction.CallbackContext context);
        void OnCycleTakeDown(InputAction.CallbackContext context);
        void OnCycleReceiveUp(InputAction.CallbackContext context);
        void OnCycleReceiveDown(InputAction.CallbackContext context);
        void OnSendWater(InputAction.CallbackContext context);
    }
}
